### ISSUE TITLE
[feat] redux, 토글, 필터링 구현

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/a-team-admin#3]
# TASK CARD

Task Description : 
- 과제 구현 위한 redux 패키지 설치 및 store 구현

Date : 2022-02-07

## to-do
- [x] redux 초기 세팅 (패키지 설치 및 스토어 구현)
- [x] requestSlice 구현 (createSlice, createSelector, createEntityAdapter 활용)
- [x] filter 별로 slice 구현: method, material, 상담 중
- [x] 토글 컴포넌트 만들기
- [x] 필터링 위한 체크박스 드롭다운 구현
