### ISSUE TITLE
[feat] 헤더 및 반응형 구현

### ISSUE THREAD

**Issue by tae100k** [wanted-pre-onboading-10/a-team-admin#6]
# TASK CARD

Task Description : 헤더 및 반응형 구현

Date : 2022.02.07

## to-do
[헤더]
- [x] 헤더 구현
- [x] 이미지 파일 관리

[반응형]
- [x] 반응형 구현 (theme에서 mobile 변수 가져오기)

[메뉴바]
- [x] 햄버거 클릭 시 회색 화면 표시
- [x] 애니메이션 설정
